# Generated by Django 3.0.6 on 2020-05-25 11:13

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20200523_2003'), ('blog', '0003_article_author'), ('blog', '0004_article_image'), ('blog', '0005_auto_20200524_2012'), ('blog', '0006_auto_20200524_2248'), ('blog', '0007_auto_20200524_2254'), ('blog', '0008_auto_20200525_0926'), ('blog', '0009_auto_20200525_1050')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, upload_to=blog.models.Article.create_path)),
                ('image_alt', models.CharField(default='default_tag', max_length=125)),
            ],
        ),
    ]
