# Generated by Django 3.0.6 on 2020-05-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.query_utils.DeferredAttribute object at 0x109682978>'),
        ),
    ]
