# Generated by Django 3.0.6 on 2020-05-24 22:54

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200524_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=blog.models.Article.create_path),
        ),
    ]
